export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const FETCH_TASKS = "FETCH_TASKS";
export const FETCH_USER_TASKS = "FETCH_USER_TASKS";
export const CHANGE_EVENT_STATUS = "CHANGE_EVENT_STATUS";
export const CHANGE_MONTH = "CHANGE_MONTH";
export const CHANGE_DATE = "CHANGE_DATE";
export const CHANGE_TYPE = "CHANGE_TYPE";
export const SET_WEEK = "SET_WEEK";
